version: '3'
services:
  respirar:
    container_name: respirar
    build: .
    ports:
      - "3001:3001"
    command: npm start
    environment:
      - KEYROCK_API_URL='http://192.168.1.42:3000'
      - KEYROCK_CLIENT_ID='256e3607-cf9e-4f7c-8e69-329a4db32abe'
      - KEYROCK_CLIENT_SECRET='e3ccbc18-ab8f-4fc7-8d6d-89e8e222b1b7'
